name: Hourly Twitter BotAdd commentMore actions

on:
  schedule:
    # Uruchamiaj co godzinę (o pełnej godzinie, np. 1:00, 2:00, itd.)
    # Zobacz https://crontab.guru/ dla pomocy z cronem
    - cron: '0 * * * *'
  workflow_dispatch: # Pozwala na ręczne uruchomienie z panelu Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest # Użyj najnowszego dostępnego środowiska Ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Zawsze używaj aktualnej wersji akcji

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Możesz wybrać inną wersję Pythona

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install tweepy requests # Alternatywnie, jeśli nie ma requirements.txt

      - name: Run Twitter Bot script
        env: # Przekazanie sekretów jako zmienne środowiskowe do skryptu
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          BOT1_ACCESS_TOKEN: ${{ secrets.BOT1_ACCESS_TOKEN }}
          BOT1_ACCESS_TOKEN_SECRET: ${{ secrets.BOT1_ACCESS_TOKEN_SECRET }}
        run: python twitter_bot.py # ZMIEŃ na nazwę Twojego pliku .py
