name: Hourly Twitter Bot

on:
  schedule:
    - cron: '0 * * * *'  # Uruchamiaj co godzinę (o pełnej godzinie)
  workflow_dispatch:      # Pozwala na ręczne uruchomienie z panelu Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # lub @v3

      - name: Set up Python
        uses: actions/setup-python@v4 # lub @v3
        with:
          python-version: '3.9' # lub inna preferowana wersja

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy requests 
          # Jeśli używasz python-dotenv lokalnie, nie jest potrzebny tutaj,
          # ale nie zaszkodzi, jeśli jest w requirements.txt

      - name: Run Twitter Bot script
        env: # Przekazanie sekretów jako zmienne środowiskowe do skryptu
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: python your_script_name.py # ZMIEŃ na nazwę Twojego pliku .py
