
### Wyjaśnienie zmiany
*   `*/2` w polu godziny oznacza "co drugą godzinę".
*   `*` w polu godziny oznacza "co każdą godzinę".

### Kompletny, zaktualizowany plik

Skopiuj poniższą treść i podmień ją w swoim pliku konfiguracyjnym GitHub Actions.

```yaml
name: Monty Twitter Bot

on:
  # 1. Uruchamiaj automatycznie co godzinę
  schedule:
    # Składnia cron: minuta godzina dzień-miesiąca miesiąc dzień-tygodnia
    # '0 * * * *' oznacza "o minucie 0, co każdą godzinę, każdego dnia".
    - cron: '0 * * * *'

  # 2. Pozwól na ręczne uruchomienie z panelu Actions na GitHubie
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Pobranie kodu z repozytorium
      - name: Checkout repository
        uses: actions/checkout@v4

      # Krok 2: Ustawienie środowiska Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Krok 3: Instalacja bibliotek z pliku requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Krok 4: Uruchomienie bota z przekazaniem sekretów
      - name: Run Twitter Bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: python twitter_bot.py
